//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trex.TaskAdministration.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Trex.TaskAdministration.Resources.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billable only.
        /// </summary>
        public static string BillableOnly {
            get {
                return ResourceManager.GetString("BillableOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm delete.
        /// </summary>
        public static string ConfirmDeleteBoxTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm that you want to delete this customer.
        /// </summary>
        public static string ConfirmDeleteCustomerLabel {
            get {
                return ResourceManager.GetString("ConfirmDeleteCustomerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm that you want to delete this project.
        /// </summary>
        public static string ConfirmDeleteProjectLabel {
            get {
                return ResourceManager.GetString("ConfirmDeleteProjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm that you want to delete this task.
        /// </summary>
        public static string ConfirmDeleteTaskLabel {
            get {
                return ResourceManager.GetString("ConfirmDeleteTaskLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm that you want to delete this timeentry.
        /// </summary>
        public static string ConfirmDeleteTimeEntryLabel {
            get {
                return ResourceManager.GetString("ConfirmDeleteTimeEntryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultants.
        /// </summary>
        public static string ConsultantLabel {
            get {
                return ResourceManager.GetString("ConsultantLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer: .
        /// </summary>
        public static string CustomerLabel {
            get {
                return ResourceManager.GetString("CustomerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date from.
        /// </summary>
        public static string DateFromLabel {
            get {
                return ResourceManager.GetString("DateFromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date to.
        /// </summary>
        public static string DateToLabel {
            get {
                return ResourceManager.GetString("DateToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project: .
        /// </summary>
        public static string ProjectsLabel {
            get {
                return ResourceManager.GetString("ProjectsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Entries.
        /// </summary>
        public static string TimeEntriesHeaderLabel {
            get {
                return ResourceManager.GetString("TimeEntriesHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total billable time.
        /// </summary>
        public static string TotalTimeBillableLabel {
            get {
                return ResourceManager.GetString("TotalTimeBillableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total time spent.
        /// </summary>
        public static string TotalTimeSpentLabel {
            get {
                return ResourceManager.GetString("TotalTimeSpentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients, Projects and Tasks.
        /// </summary>
        public static string TreeHeaderLabel {
            get {
                return ResourceManager.GetString("TreeHeaderLabel", resourceCulture);
            }
        }
    }
}
