//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.60310.0
// 
namespace Trex.ServiceModel.FileDownloadService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="FileDownloadService.IFileDownloadService")]
    public interface IFileDownloadService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:IFileDownloadService/DownloadTemplateFile", ReplyAction="urn:IFileDownloadService/DownloadTemplateFileResponse")]
        System.IAsyncResult BeginDownloadTemplateFile(int templateId, System.AsyncCallback callback, object asyncState);
        
        byte[] EndDownloadTemplateFile(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:IFileDownloadService/DownloadPdfFile", ReplyAction="urn:IFileDownloadService/DownloadPdfFileResponse")]
        System.IAsyncResult BeginDownloadPdfFile(System.Guid invoiceGuid, int format, System.AsyncCallback callback, object asyncState);
        
        byte[] EndDownloadPdfFile(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:IFileDownloadService/FinalizeInvoices", ReplyAction="urn:IFileDownloadService/FinalizeInvoicesResponse")]
        System.IAsyncResult BeginFinalizeInvoices(System.Collections.ObjectModel.ObservableCollection<int> invoiceIds, bool isPreview, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<Trex.ServiceContracts.ServerResponse> EndFinalizeInvoices(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:IFileDownloadService/DeleteInvoiceFiles", ReplyAction="urn:IFileDownloadService/DeleteInvoiceFilesResponse")]
        System.IAsyncResult BeginDeleteInvoiceFiles(int invoiceId, System.AsyncCallback callback, object asyncState);
        
        Trex.ServiceContracts.ServerResponse EndDeleteInvoiceFiles(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:IFileDownloadService/ValidateTemplate", ReplyAction="urn:IFileDownloadService/ValidateTemplateResponse")]
        System.IAsyncResult BeginValidateTemplate(byte[] data, int TemplateType, System.AsyncCallback callback, object asyncState);
        
        Trex.ServiceContracts.ServerResponse EndValidateTemplate(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFileDownloadServiceChannel : Trex.ServiceModel.FileDownloadService.IFileDownloadService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DownloadTemplateFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DownloadTemplateFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public byte[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DownloadPdfFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DownloadPdfFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public byte[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FinalizeInvoicesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public FinalizeInvoicesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Trex.ServiceContracts.ServerResponse> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Trex.ServiceContracts.ServerResponse>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeleteInvoiceFilesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DeleteInvoiceFilesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Trex.ServiceContracts.ServerResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Trex.ServiceContracts.ServerResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValidateTemplateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ValidateTemplateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Trex.ServiceContracts.ServerResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Trex.ServiceContracts.ServerResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileDownloadServiceClient : System.ServiceModel.ClientBase<Trex.ServiceModel.FileDownloadService.IFileDownloadService>, Trex.ServiceModel.FileDownloadService.IFileDownloadService {
        
        private BeginOperationDelegate onBeginDownloadTemplateFileDelegate;
        
        private EndOperationDelegate onEndDownloadTemplateFileDelegate;
        
        private System.Threading.SendOrPostCallback onDownloadTemplateFileCompletedDelegate;
        
        private BeginOperationDelegate onBeginDownloadPdfFileDelegate;
        
        private EndOperationDelegate onEndDownloadPdfFileDelegate;
        
        private System.Threading.SendOrPostCallback onDownloadPdfFileCompletedDelegate;
        
        private BeginOperationDelegate onBeginFinalizeInvoicesDelegate;
        
        private EndOperationDelegate onEndFinalizeInvoicesDelegate;
        
        private System.Threading.SendOrPostCallback onFinalizeInvoicesCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteInvoiceFilesDelegate;
        
        private EndOperationDelegate onEndDeleteInvoiceFilesDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteInvoiceFilesCompletedDelegate;
        
        private BeginOperationDelegate onBeginValidateTemplateDelegate;
        
        private EndOperationDelegate onEndValidateTemplateDelegate;
        
        private System.Threading.SendOrPostCallback onValidateTemplateCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public FileDownloadServiceClient() {
        }
        
        public FileDownloadServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileDownloadServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileDownloadServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileDownloadServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<DownloadTemplateFileCompletedEventArgs> DownloadTemplateFileCompleted;
        
        public event System.EventHandler<DownloadPdfFileCompletedEventArgs> DownloadPdfFileCompleted;
        
        public event System.EventHandler<FinalizeInvoicesCompletedEventArgs> FinalizeInvoicesCompleted;
        
        public event System.EventHandler<DeleteInvoiceFilesCompletedEventArgs> DeleteInvoiceFilesCompleted;
        
        public event System.EventHandler<ValidateTemplateCompletedEventArgs> ValidateTemplateCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Trex.ServiceModel.FileDownloadService.IFileDownloadService.BeginDownloadTemplateFile(int templateId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDownloadTemplateFile(templateId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        byte[] Trex.ServiceModel.FileDownloadService.IFileDownloadService.EndDownloadTemplateFile(System.IAsyncResult result) {
            return base.Channel.EndDownloadTemplateFile(result);
        }
        
        private System.IAsyncResult OnBeginDownloadTemplateFile(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int templateId = ((int)(inValues[0]));
            return ((Trex.ServiceModel.FileDownloadService.IFileDownloadService)(this)).BeginDownloadTemplateFile(templateId, callback, asyncState);
        }
        
        private object[] OnEndDownloadTemplateFile(System.IAsyncResult result) {
            byte[] retVal = ((Trex.ServiceModel.FileDownloadService.IFileDownloadService)(this)).EndDownloadTemplateFile(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDownloadTemplateFileCompleted(object state) {
            if ((this.DownloadTemplateFileCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DownloadTemplateFileCompleted(this, new DownloadTemplateFileCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DownloadTemplateFileAsync(int templateId) {
            this.DownloadTemplateFileAsync(templateId, null);
        }
        
        public void DownloadTemplateFileAsync(int templateId, object userState) {
            if ((this.onBeginDownloadTemplateFileDelegate == null)) {
                this.onBeginDownloadTemplateFileDelegate = new BeginOperationDelegate(this.OnBeginDownloadTemplateFile);
            }
            if ((this.onEndDownloadTemplateFileDelegate == null)) {
                this.onEndDownloadTemplateFileDelegate = new EndOperationDelegate(this.OnEndDownloadTemplateFile);
            }
            if ((this.onDownloadTemplateFileCompletedDelegate == null)) {
                this.onDownloadTemplateFileCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDownloadTemplateFileCompleted);
            }
            base.InvokeAsync(this.onBeginDownloadTemplateFileDelegate, new object[] {
                        templateId}, this.onEndDownloadTemplateFileDelegate, this.onDownloadTemplateFileCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Trex.ServiceModel.FileDownloadService.IFileDownloadService.BeginDownloadPdfFile(System.Guid invoiceGuid, int format, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDownloadPdfFile(invoiceGuid, format, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        byte[] Trex.ServiceModel.FileDownloadService.IFileDownloadService.EndDownloadPdfFile(System.IAsyncResult result) {
            return base.Channel.EndDownloadPdfFile(result);
        }
        
        private System.IAsyncResult OnBeginDownloadPdfFile(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Guid invoiceGuid = ((System.Guid)(inValues[0]));
            int format = ((int)(inValues[1]));
            return ((Trex.ServiceModel.FileDownloadService.IFileDownloadService)(this)).BeginDownloadPdfFile(invoiceGuid, format, callback, asyncState);
        }
        
        private object[] OnEndDownloadPdfFile(System.IAsyncResult result) {
            byte[] retVal = ((Trex.ServiceModel.FileDownloadService.IFileDownloadService)(this)).EndDownloadPdfFile(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDownloadPdfFileCompleted(object state) {
            if ((this.DownloadPdfFileCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DownloadPdfFileCompleted(this, new DownloadPdfFileCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DownloadPdfFileAsync(System.Guid invoiceGuid, int format) {
            this.DownloadPdfFileAsync(invoiceGuid, format, null);
        }
        
        public void DownloadPdfFileAsync(System.Guid invoiceGuid, int format, object userState) {
            if ((this.onBeginDownloadPdfFileDelegate == null)) {
                this.onBeginDownloadPdfFileDelegate = new BeginOperationDelegate(this.OnBeginDownloadPdfFile);
            }
            if ((this.onEndDownloadPdfFileDelegate == null)) {
                this.onEndDownloadPdfFileDelegate = new EndOperationDelegate(this.OnEndDownloadPdfFile);
            }
            if ((this.onDownloadPdfFileCompletedDelegate == null)) {
                this.onDownloadPdfFileCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDownloadPdfFileCompleted);
            }
            base.InvokeAsync(this.onBeginDownloadPdfFileDelegate, new object[] {
                        invoiceGuid,
                        format}, this.onEndDownloadPdfFileDelegate, this.onDownloadPdfFileCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Trex.ServiceModel.FileDownloadService.IFileDownloadService.BeginFinalizeInvoices(System.Collections.ObjectModel.ObservableCollection<int> invoiceIds, bool isPreview, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginFinalizeInvoices(invoiceIds, isPreview, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<Trex.ServiceContracts.ServerResponse> Trex.ServiceModel.FileDownloadService.IFileDownloadService.EndFinalizeInvoices(System.IAsyncResult result) {
            return base.Channel.EndFinalizeInvoices(result);
        }
        
        private System.IAsyncResult OnBeginFinalizeInvoices(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Collections.ObjectModel.ObservableCollection<int> invoiceIds = ((System.Collections.ObjectModel.ObservableCollection<int>)(inValues[0]));
            bool isPreview = ((bool)(inValues[1]));
            return ((Trex.ServiceModel.FileDownloadService.IFileDownloadService)(this)).BeginFinalizeInvoices(invoiceIds, isPreview, callback, asyncState);
        }
        
        private object[] OnEndFinalizeInvoices(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Trex.ServiceContracts.ServerResponse> retVal = ((Trex.ServiceModel.FileDownloadService.IFileDownloadService)(this)).EndFinalizeInvoices(result);
            return new object[] {
                    retVal};
        }
        
        private void OnFinalizeInvoicesCompleted(object state) {
            if ((this.FinalizeInvoicesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.FinalizeInvoicesCompleted(this, new FinalizeInvoicesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void FinalizeInvoicesAsync(System.Collections.ObjectModel.ObservableCollection<int> invoiceIds, bool isPreview) {
            this.FinalizeInvoicesAsync(invoiceIds, isPreview, null);
        }
        
        public void FinalizeInvoicesAsync(System.Collections.ObjectModel.ObservableCollection<int> invoiceIds, bool isPreview, object userState) {
            if ((this.onBeginFinalizeInvoicesDelegate == null)) {
                this.onBeginFinalizeInvoicesDelegate = new BeginOperationDelegate(this.OnBeginFinalizeInvoices);
            }
            if ((this.onEndFinalizeInvoicesDelegate == null)) {
                this.onEndFinalizeInvoicesDelegate = new EndOperationDelegate(this.OnEndFinalizeInvoices);
            }
            if ((this.onFinalizeInvoicesCompletedDelegate == null)) {
                this.onFinalizeInvoicesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnFinalizeInvoicesCompleted);
            }
            base.InvokeAsync(this.onBeginFinalizeInvoicesDelegate, new object[] {
                        invoiceIds,
                        isPreview}, this.onEndFinalizeInvoicesDelegate, this.onFinalizeInvoicesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Trex.ServiceModel.FileDownloadService.IFileDownloadService.BeginDeleteInvoiceFiles(int invoiceId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeleteInvoiceFiles(invoiceId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Trex.ServiceContracts.ServerResponse Trex.ServiceModel.FileDownloadService.IFileDownloadService.EndDeleteInvoiceFiles(System.IAsyncResult result) {
            return base.Channel.EndDeleteInvoiceFiles(result);
        }
        
        private System.IAsyncResult OnBeginDeleteInvoiceFiles(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int invoiceId = ((int)(inValues[0]));
            return ((Trex.ServiceModel.FileDownloadService.IFileDownloadService)(this)).BeginDeleteInvoiceFiles(invoiceId, callback, asyncState);
        }
        
        private object[] OnEndDeleteInvoiceFiles(System.IAsyncResult result) {
            Trex.ServiceContracts.ServerResponse retVal = ((Trex.ServiceModel.FileDownloadService.IFileDownloadService)(this)).EndDeleteInvoiceFiles(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDeleteInvoiceFilesCompleted(object state) {
            if ((this.DeleteInvoiceFilesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteInvoiceFilesCompleted(this, new DeleteInvoiceFilesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteInvoiceFilesAsync(int invoiceId) {
            this.DeleteInvoiceFilesAsync(invoiceId, null);
        }
        
        public void DeleteInvoiceFilesAsync(int invoiceId, object userState) {
            if ((this.onBeginDeleteInvoiceFilesDelegate == null)) {
                this.onBeginDeleteInvoiceFilesDelegate = new BeginOperationDelegate(this.OnBeginDeleteInvoiceFiles);
            }
            if ((this.onEndDeleteInvoiceFilesDelegate == null)) {
                this.onEndDeleteInvoiceFilesDelegate = new EndOperationDelegate(this.OnEndDeleteInvoiceFiles);
            }
            if ((this.onDeleteInvoiceFilesCompletedDelegate == null)) {
                this.onDeleteInvoiceFilesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteInvoiceFilesCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteInvoiceFilesDelegate, new object[] {
                        invoiceId}, this.onEndDeleteInvoiceFilesDelegate, this.onDeleteInvoiceFilesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Trex.ServiceModel.FileDownloadService.IFileDownloadService.BeginValidateTemplate(byte[] data, int TemplateType, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginValidateTemplate(data, TemplateType, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Trex.ServiceContracts.ServerResponse Trex.ServiceModel.FileDownloadService.IFileDownloadService.EndValidateTemplate(System.IAsyncResult result) {
            return base.Channel.EndValidateTemplate(result);
        }
        
        private System.IAsyncResult OnBeginValidateTemplate(object[] inValues, System.AsyncCallback callback, object asyncState) {
            byte[] data = ((byte[])(inValues[0]));
            int TemplateType = ((int)(inValues[1]));
            return ((Trex.ServiceModel.FileDownloadService.IFileDownloadService)(this)).BeginValidateTemplate(data, TemplateType, callback, asyncState);
        }
        
        private object[] OnEndValidateTemplate(System.IAsyncResult result) {
            Trex.ServiceContracts.ServerResponse retVal = ((Trex.ServiceModel.FileDownloadService.IFileDownloadService)(this)).EndValidateTemplate(result);
            return new object[] {
                    retVal};
        }
        
        private void OnValidateTemplateCompleted(object state) {
            if ((this.ValidateTemplateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ValidateTemplateCompleted(this, new ValidateTemplateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ValidateTemplateAsync(byte[] data, int TemplateType) {
            this.ValidateTemplateAsync(data, TemplateType, null);
        }
        
        public void ValidateTemplateAsync(byte[] data, int TemplateType, object userState) {
            if ((this.onBeginValidateTemplateDelegate == null)) {
                this.onBeginValidateTemplateDelegate = new BeginOperationDelegate(this.OnBeginValidateTemplate);
            }
            if ((this.onEndValidateTemplateDelegate == null)) {
                this.onEndValidateTemplateDelegate = new EndOperationDelegate(this.OnEndValidateTemplate);
            }
            if ((this.onValidateTemplateCompletedDelegate == null)) {
                this.onValidateTemplateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnValidateTemplateCompleted);
            }
            base.InvokeAsync(this.onBeginValidateTemplateDelegate, new object[] {
                        data,
                        TemplateType}, this.onEndValidateTemplateDelegate, this.onValidateTemplateCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Trex.ServiceModel.FileDownloadService.IFileDownloadService CreateChannel() {
            return new FileDownloadServiceClientChannel(this);
        }
        
        private class FileDownloadServiceClientChannel : ChannelBase<Trex.ServiceModel.FileDownloadService.IFileDownloadService>, Trex.ServiceModel.FileDownloadService.IFileDownloadService {
            
            public FileDownloadServiceClientChannel(System.ServiceModel.ClientBase<Trex.ServiceModel.FileDownloadService.IFileDownloadService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginDownloadTemplateFile(int templateId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = templateId;
                System.IAsyncResult _result = base.BeginInvoke("DownloadTemplateFile", _args, callback, asyncState);
                return _result;
            }
            
            public byte[] EndDownloadTemplateFile(System.IAsyncResult result) {
                object[] _args = new object[0];
                byte[] _result = ((byte[])(base.EndInvoke("DownloadTemplateFile", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginDownloadPdfFile(System.Guid invoiceGuid, int format, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = invoiceGuid;
                _args[1] = format;
                System.IAsyncResult _result = base.BeginInvoke("DownloadPdfFile", _args, callback, asyncState);
                return _result;
            }
            
            public byte[] EndDownloadPdfFile(System.IAsyncResult result) {
                object[] _args = new object[0];
                byte[] _result = ((byte[])(base.EndInvoke("DownloadPdfFile", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginFinalizeInvoices(System.Collections.ObjectModel.ObservableCollection<int> invoiceIds, bool isPreview, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = invoiceIds;
                _args[1] = isPreview;
                System.IAsyncResult _result = base.BeginInvoke("FinalizeInvoices", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<Trex.ServiceContracts.ServerResponse> EndFinalizeInvoices(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<Trex.ServiceContracts.ServerResponse> _result = ((System.Collections.ObjectModel.ObservableCollection<Trex.ServiceContracts.ServerResponse>)(base.EndInvoke("FinalizeInvoices", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginDeleteInvoiceFiles(int invoiceId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = invoiceId;
                System.IAsyncResult _result = base.BeginInvoke("DeleteInvoiceFiles", _args, callback, asyncState);
                return _result;
            }
            
            public Trex.ServiceContracts.ServerResponse EndDeleteInvoiceFiles(System.IAsyncResult result) {
                object[] _args = new object[0];
                Trex.ServiceContracts.ServerResponse _result = ((Trex.ServiceContracts.ServerResponse)(base.EndInvoke("DeleteInvoiceFiles", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginValidateTemplate(byte[] data, int TemplateType, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = data;
                _args[1] = TemplateType;
                System.IAsyncResult _result = base.BeginInvoke("ValidateTemplate", _args, callback, asyncState);
                return _result;
            }
            
            public Trex.ServiceContracts.ServerResponse EndValidateTemplate(System.IAsyncResult result) {
                object[] _args = new object[0];
                Trex.ServiceContracts.ServerResponse _result = ((Trex.ServiceContracts.ServerResponse)(base.EndInvoke("ValidateTemplate", _args, result)));
                return _result;
            }
        }
    }
}
